# Generated by Django 3.2.7 on 2021-10-14 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight_shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='roadfreightpark',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roadfreightpark',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='freight_shipping.district'),
        ),
        migrations.AlterField(
            model_name='roadfreightpark',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight_shipping.route'),
        ),
        migrations.AlterField(
            model_name='roadfreightpark',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='freight_shipping.vehiclemodel'),
        ),
    ]
