# Generated by Django 3.2.7 on 2021-10-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0002_auto_20211014_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'default_permissions': (), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='roadfreightpark',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'default_permissions': ()},
        ),
    ]
