# Generated by Django 3.2.7 on 2021-10-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0004_alter_roadfreightpark_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadfreightpark',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='freight_shipping.route'),
        ),
    ]
