# Generated by Django 3.2.7 on 2021-10-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0005_alter_roadfreightpark_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadfreightpark',
            name='route',
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freight_shipping.roadfreightpark'),
        ),
    ]
