# Generated by Django 3.2.7 on 2021-10-23 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight_shipping', '0007_alter_route_vehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadFreightPark',
            new_name='Vehicle',
        ),
    ]
