# Generated by Django 3.2.7 on 2021-10-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0008_rename_roadfreightpark_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='freight_shipping.vehicle'),
        ),
    ]
