# Generated by Django 3.2.7 on 2021-10-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0009_alter_route_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='next_location',
            new_name='next_route_id',
        ),
    ]
