# Generated by Django 3.2.7 on 2021-10-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0010_rename_next_location_route_next_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='next_route_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
