# Generated by Django 3.2.7 on 2021-11-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0011_alter_route_next_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dangerous_goods',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='temperature_control',
            field=models.BooleanField(default=False),
        ),
    ]
