# Generated by Django 3.2.7 on 2021-11-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0013_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='route',
        ),
        migrations.AddField(
            model_name='order',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure', to='freight_shipping.route'),
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='freight_shipping.route'),
        ),
    ]
