# Generated by Django 3.2.7 on 2021-11-27 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight_shipping', '0014_auto_20211120_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight_shipping.order'),
        ),
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departure', to='freight_shipping.district')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destination', to='freight_shipping.district')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_order',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='freight_shipping.completedorder'),
        ),
    ]
