# Generated by Django 3.2.7 on 2021-11-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0015_auto_20211127_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.AddField(
            model_name='order',
            name='departure_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_route', to='freight_shipping.route'),
        ),
        migrations.AddField(
            model_name='order',
            name='destination_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_route', to='freight_shipping.route'),
        ),
    ]
