# Generated by Django 3.2.7 on 2021-11-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight_shipping', '0016_auto_20211127_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='departure_district',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='departure_district', to='freight_shipping.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='destination_district',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, related_name='destination_district', to='freight_shipping.district'),
            preserve_default=False,
        ),
    ]
